### ISSUE TITLE
Feedback on Milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_OlympicMedalPrediction#19]
@aaronquinton and @Sayanti86 , you have done a great job! 

Here are some remaining issues:

- [x] Add instructions on how to run your analysis in the main readme
- [x] Add version information to your dependencies
- [x] Add links to your readme whenever you mention a specific folder within your repository. Same thing applies to your report.
- [x] I spotted multiple spelling mistakes. Take a closer look and correct for those.

**Suggestions:**

- The way you have tabulated the scripts based on order looks great. It is very helpful in understanding your analysis. An alternative is to include a flow chart/dependency diagram on your readme.  

- You have chosen to draw a map of your repository in the main readme which I found very helpful. However, a better way to do this would be to explain each folder via a readme within each folder. In other words, you can add readme for each folder within your repository. Then, you can only add the links to these sections on the main readme. This is a strong suggestion, but if you find it more useful this way, no problem :)

**Comment by aaronquinton** [comment]
Thank you for your feedback! we have addressed your points and suggestions and incorporated them in our project
